[tools]
node = "lts"
rust = "latest"
foundry = "1.5.1"
pnpm = "latest"
bun = "latest"
uv = "latest"
"cargo:https://github.com/itsjunetime/tdf" = "latest"
"npm:@marp-team/marp-cli" = "latest"

[settings]
auto_install = true
not_found_auto_install = true
