onboarding = false

[update]
channel = "stable"
version_check = true
manifest_check = true

[terminal]
shell_mode = "auto"
new_cwd = "follow"

[worktrees]
directory = "~/work/herdr-worktrees"

[theme]
name = "terminal"

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_sort = "priority"
confirm_close = true
prompt_new_tab_name = true

[ui.toast]
delivery = "herdr"
delay_seconds = 2

[ui.toast.herdr]
position = "bottom-right"

[ui.toast.clipboard]
enabled = true
position = "bottom-center"

[ui.sound]
enabled = false

[session]
resume_agents_on_restore = true

[experimental]
reveal_hidden_cursor_for_cjk_ime = true
cjk_ime_agents = ["claude", "codex", "kiro", "cursor", "opencode"]
switch_ascii_input_source_in_prefix = true
pane_history = false
allow_nested = false
kitty_graphics = false
